# Generated by Django 6.0.7 on 2026-08-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='rotating_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
