# Generated by Django 6.0.7 on 2026-08-06 19:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0002_classsession_rotating_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
