# Generated by Django 6.0.7 on 2026-08-05 00:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='last_sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
